### ISSUE TITLE
[BigDoorsPhysics] Unhandled exception number 65536 occured in onPacketSending(PacketEvent) for BigDoorsPhysics

### ISSUE THREAD

**Issue by TomLewis** [bonn2/BigDoorsPhysics#13]
Lots of these spamming in my console
https://gist.github.com/TomLewis/da54387a4e2fbcff86f2ccd979af3bcc

**Comment by bonn2** [comment]
Are you on the latest version? Because I believe I fixed this in 2.3.5

**Comment by TomLewis** [comment]
Nope, using 2.4.0 by the looks of things! I will get it updated

**Comment by bonn2** [comment]
Has updating resolved the issue?

**Comment by bonn2** [comment]
Closing as Resolved
