### ISSUE TITLE
Needs update to 1.21

### ISSUE THREAD

**Issue by vampiregoat699** [bonn2/BigDoorsPhysics#29]
Needs update to 1.21, looked on the site for a dev version and it is not there either.

**Comment by bonn2** [comment]
Fixed in 32c0da9dead0863647e25c9718e79826121ed4d3

**Comment by vampiregoat699** [comment]
Any chance to get the opener updated I love using that

JML

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by bonn2** [comment]
I'm not the maintainer of Opener, but if I have some free time I'll look into it.
