### ISSUE TITLE
Barrier blocks stay after doors shut, locking people in!

### ISSUE THREAD

**Issue by TomLewis** [bonn2/BigDoorsPhysics#8]
Hi, we're using purpur 1.18 and recently installed BigDoorsPhysics, were having an issue with doors leaving barrier blocks after they are shut! Permanenty, players can't break these which requires staff to remove them manually!

Were using grief prevention if that hasn't been tested with the plugin?

Could you look into a resolve for this bug and also way to clear up outside existing doors that have had barrier blocks left there!

Thanks

**Comment by bonn2** [comment]
This sounds like an issue I have fixed before.

What version of Purpur, Bigdoors and BigdoorsPhysics are you running, so I can try to recreate.

Also you mentioned GriefPrevention, does this only happen in claimed areas or all areas?

Lastly, does this just happen occasionally and if so any idea as to why?

**Comment by TomLewis** [comment]
> What version of Purpur, Bigdoors and BigdoorsPhysics are you running, so I can try to recreate.

The last 1.18.2 that got released: git-Purpur-1632 (MC: 1.18.2) https://api.purpurmc.org/v2/purpur/1.18.2/1632/download
The latest BigDoors version Alpha 0.1.8.44 (b1133)
The laest BigdoorsPhysics, I only installed it a few days ago.

> does this only happen in claimed areas or all areas?
Not sure.

> Lastly, does this just happen occasionally and if so any idea as to something that may be triggering it?
We cant find a way to reproduce, if there is some sort of debugging that we can turn on that would be very handy to figure out why its doing this.

Im acting a third party on behalf of players, I have asked them to explain in more detail in this ticket, I will ask them again.

**Comment by THEjpcello** [comment]
https://github.com/bonn2/BigDoorsPhysics/assets/133015548/e2e79ca9-25d6-4d31-b757-ecac60b897c0

**Comment by THEjpcello** [comment]
https://github.com/bonn2/BigDoorsPhysics/assets/133015548/0fa7c270-5694-47b1-83e3-cf6f6f3bb6c3

while trying the portcullis no barrier block appeared at first. then suddenly the door got blocked by one as seen in the video

**Comment by THEjpcello** [comment]
https://github.com/bonn2/BigDoorsPhysics/assets/133015548/c610d1a8-a303-4c1f-94ee-17cff4be3cc2

this portculli only spawns barrier blocks while opening/closing
in the end you can see that I'm pushed through another block

**Comment by THEjpcello** [comment]
update to the last post:

In order to prevent the glitch in the base he made a second layer of stone in the floor. which resulted in him glitching only one block in the floor and no longer through.
After opening the door again he got glitched on top of the portuclli?!
He got down again and noticed that now 2 barrier blocks have spawned. They now blocked the portculli do go down again.

Even after deleting the portculli the barrier blocks remain there


![barrier block under the portculli](https://github.com/bonn2/BigDoorsPhysics/assets/133015548/baee457f-8dbd-404b-b719-d8c366a6e315)

![barrier block 2 under the portculli](https://github.com/bonn2/BigDoorsPhysics/assets/133015548/d3751298-8043-4244-a659-c673a376a030)

**Comment by THEjpcello** [comment]
we managed to produce a barrier block with a sliding door by glitching when it's opening

**Comment by THEjpcello** [comment]
the last video was in unclaimed land

**Comment by TomLewis** [comment]
Fantastic news, thanks for pushing this fix, I will get this live for tomorrows reboot on PirateCraft!

>  how it took this long for someone else to notice.
Took us less than 10 minutes of the plugin being live somehow haha

If you ever need anything tested by a group of players, we can test it on PirateCraft and find oddities like this fast!

Big thanks @THEjpcello JP for doing some extra testing and those videos are helpful!
